// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Kitabe2ML.Model
{
    public class ModelInput
    {
        [ColumnName("Rating_Id"), LoadColumn(0)]
        public float Rating_Id { get; set; }


        [ColumnName("Id"), LoadColumn(1)]
        public float Id { get; set; }


        [ColumnName("R_Id"), LoadColumn(2)]
        public float R_Id { get; set; }


        [ColumnName("Rating"), LoadColumn(3)]
        public float Rating { get; set; }


    }
}
